# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KgnmQrImviDaJAFEEhipIUlYk9cc94uK
"""

import streamlit as st
import random

st.set_page_config(layout="wide")
st.write('Hello Na!')

if st.button('Generate Random Number'):
    random_number = random.randint(1, 100)
    st.write(f'Random Number: {random_number}')